admin:
  1:
    email: "pede@icloud.couk"
    # password: password
    password: "$argon2i$v=19$m=65536,t=4,p=1$ZTJLaGYvdDJtMUVKTFJCWQ$vHhV73SOuPb24C2fg88oQLwUC1a7eKHnfC4CEHV5Ats"
    roles: 
      - "ROLE_SUPER_ADMIN"
  2:
    email: "proin.sed.turpis@protonmail.edu"
    # password: babeudi
    password: "$argon2i$v=19$m=65536,t=4,p=1$ZnplSklHYU13aC9FSEp3eQ$SHRulI8gt/LqmH7MjBJ1lVZJE3Ec4ReBzNX2Jsq5JGg"
    roles:
      - "ROLE_ADMIN"
  3:
    email: "nonummy.ac@icloud.edu"
    # password: helloworld
    password: "$argon2i$v=19$m=65536,t=4,p=1$YWVmdVREdjR6aDJwbkIvaw$ppluxlgtQ1YVgyEG3vWTlaKVxnJ0qb1h20giVPzHp08"
    roles:
      - "ROLE_ADMIN"
  4:
    email: "luctus@icloud.ca"
    # password: admin
    password: "$argon2i$v=19$m=65536,t=4,p=1$OFJ4cFllNnRoc3FxbHVXOA$7k9exvWZ2nPIcsWU/v4Z8h6n18LWL6v8RPSsZIsYbLU"
    roles:
      - "ROLE_ADMIN"
  5:
    email: "bibendum.sed@protonmail.com"
    # password: 1234
    password: "$argon2i$v=19$m=65536,t=4,p=1$dGpLZ2xyZDZpbXJhNzVGWQ$s0X63CtwYOEm7Jjj4gAkCnE7H2ClGg5AdQcMOvt9f1Y"
    roles:
      - "ROLE_ADMIN"
  6:
    email: "pacolu@proteimail.com"
    # password: 60pdOulo$
    password: "$argon2i$v=19$m=65536,t=4,p=1$VTZpS21vZEhZeGtEWDZLUw$tO46fN91BV35uNiyc8zw/alUM2LLtyq/vF+4YQTbc+g"
    roles:
      - "ROLE_SUPER_ADMIN"

ckeditor:
  1:
    pageName: "HomePage"
    zone: "zone"
    content: "<p>Texte de pr&eacute;sentaion du CSE de Saint-Vincent</p>"
  2:
    pageName: "AboutUs"
    zone: "actions"
    content: "<p>Les diff&eacute;rentes actions men&eacute;es:</p><ul><li>offres permanentes</li><li>offres limit&eacute;es</li><li>reherche de partenariats</li><li>syndicats</li><li>votes</li><li>&eacute;coute</li></ul>"
  3:
    pageName: "AboutUs"
    zone: "rules"
    content: "<h3><strong>Article 1 :</strong></h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In metus magna, cursus nec felis a, mattis malesuada risus. Mauris et mi nec urna accumsan iaculis. In congue erat eu sem finibus eleifend. Duis vestibulum dui nec egestas eleifend. Nulla molestie metus ac orci finibus semper. Nam non commodo risus. Duis sollicitudin et sapien quis interdum. Donec ultrices condimentum lectus, ac pellentesque tellus egestas eu. Sed scelerisque quam et nisl finibus, eu molestie tortor varius. Cras ex nulla, ornare non velit vitae, porta ultricies eros.</p><p>Pellentesque aliquet metus id magna tristique mattis. Nullam nisi augue, auctor non euismod et, tempus id neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In rhoncus venenatis lorem, ut mollis erat pellentesque in. Sed tristique odio vel mauris lacinia, sit amet euismod ipsum sollicitudin. Fusce a lectus cursus, luctus elit nec, sagittis tortor. Vestibulum enim nisl, accumsan non imperdiet a, gravida sed purus. Cras tristique lacus augue, placerat finibus nulla volutpat eget. Ut viverra porttitor ultrices. Nullam maximus porta eros eu consectetur. Praesent id lacus orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p><h3>&nbsp;</h3><h3><strong>Article 2 :</strong></h3><p>&nbsp;</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In metus magna, cursus nec felis a, mattis malesuada risus. Mauris et mi nec urna accumsan iaculis. In congue erat eu sem finibus eleifend. Duis vestibulum dui nec egestas eleifend. Nulla molestie metus ac orci finibus semper. Nam non commodo risus. Duis sollicitudin et sapien quis interdum. Donec ultrices condimentum lectus, ac pellentesque tellus egestas eu. Sed scelerisque quam et nisl finibus, eu molestie tortor varius. Cras ex nulla, ornare non velit vitae, porta ultricies eros.</p><p>Pellentesque aliquet metus id magna tristique mattis. Nullam nisi augue, auctor non euismod et, tempus id neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In rhoncus venenatis lorem, ut mollis erat pellentesque in. Sed tristique odio vel mauris lacinia, sit amet euismod ipsum sollicitudin. Fusce a lectus cursus, luctus elit nec, sagittis tortor. Vestibulum enim nisl, accumsan non imperdiet a, gravida sed purus. Cras tristique lacus augue, placerat finibus nulla volutpat eget. Ut viverra porttitor ultrices. Nullam maximus porta eros eu consectetur. Praesent id lacus orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
  4:
    pageName: "Client"
    zone: "email"
    content: "<p><strong>cse@lyceestvincent.net</strong></p>"
  5:
    pageName: "Client"
    zone: "phone"
    content: "<p><strong>0623456789</strong></p>"
  6:
    pageName: "Client"
    zone: "place"
    content: "<p>Bureau du CSE - 1er &eacute;tage b&acirc;timent Saint-Vincent</p>"

member:
  1:
    firstName: "Greg"
    lastName: "Lefils"
    profil: "Greg.jpg"
    function: "Boss"
  2:
    firstName: "Jean-Phi"
    lastName: "Ling"
    profil: "Jean-Phi.jpg"
    function: "Responsable sourire"
  3:
    firstName: "Walter"
    lastName: "Deloris"
    profil: "Walter.jpg"
    function: UX/UI Designer
  4:
    firstName: "Charlotte"
    lastName: "Hofrès"
    profil: "Charlotte.jpg"
    function: "Ressource humaine"
  5:
    firstName: "Anne"
    lastName: "Nonym"
    profil: null
    function: "Arbitre à mi-temps"

partnership:
  1:
    name: "Google"
    image: "googleLogo.png"
    description: "1er navigateur utilisé dans le monde !"
    link: "https://www.google.com/"
  2:
    name: "Pathé"
    image: "patheLogo.png"
    description: "Plus gros cinéma de france !"
    link: "https://www.pathe.fr/"
  3:
    name: "Mental Works"
    image: "mentalWorksLogo.png"
    description: "Entreprise de création de visibilité numérique"
    link: "https://www.mentalworks.fr/"
  4:
    name: "Macdonald's"
    image: "macdonaldsLogo.png"
    description: "1er fastfood de france !"
    link: "https://www.mcdonalds.fr/"
  5:
    name: "CNIL"
    image: "logoCNIL.jpg"
    description: "Expert en sécurité informatique"
    link: "https://www.cnil.fr/"
  6:
    name: "OA"
    image: null
    description: "Organisation Annonyme"
    link: "https://www.oa.fr/"

ticketing:
  1:
    slug: "1-cinema" 
    name: "Cinéma"
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    dateStart:
      class: DateTime
      value: "2023-07-05" 
    dateEnd:
      class: DateTime
      value: "2023-07-05"
    dateCreate:
      class: DateTime
      value: "2023-07-05" 
    numberMinPlace: 50
    orderNumber: null
    type: "permanente"
    partnership:
      entity: partnership
      id: 2
  2:
    slug: "2-parc-asterix" 
    name: "Parc Astérix"
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    dateStart:
      class: DateTime
      value: "2023-07-05" 
    dateEnd:
      class: DateTime
      value: "2023-07-05"
    dateCreate:
      class: DateTime
      value: "2023-07-05" 
    numberMinPlace: 20
    orderNumber: null
    type: "permanente"
    partnership: null
  3:
    slug: "3-bon-decathlon" 
    name: "Bon Décathlon"
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    dateStart:
      class: DateTime
      value: "2023-07-05" 
    dateEnd:
      class: DateTime
      value: "2023-07-05"
    dateCreate:
      class: DateTime
      value: "2023-07-05" 
    numberMinPlace: 10
    orderNumber: null
    type: "permanente"
    partnership: null
  4:
    slug: "4-voyage-rome" 
    name: "Voyage Rome"
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    dateStart:
      class: DateTime
      value: "2023-07-05" 
    dateEnd:
      class: DateTime
      value: "2023-07-05"
    dateCreate:
      class: DateTime
      value: "2022-03-01" 
    numberMinPlace: 10 
    orderNumber: null
    type: "permanente"
    partnership: null
  5:
    slug: "5-convention-manga" 
    name: "Convention Manga"
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    dateStart:
      class: DateTime
      value: "2023-07-05" 
    dateEnd:
      class: DateTime
      value: "2023-07-05"
    dateCreate:
      class: DateTime
      value: "2023-07-05" 
    numberMinPlace: 30
    orderNumber: null
    type: "permanente"
    partnership: null
  6:
    slug: "6-lorem" 
    name: "Lorem"
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    dateStart:
      class: DateTime
      value: "2023-07-05" 
    dateEnd:
      class: DateTime
      value: "2023-07-05"
    dateCreate:
      class: DateTime
      value: "2022-08-07" 
    numberMinPlace: null
    orderNumber: 2
    type: "limitée"
    partnership: null
  7:
    slug: "7-ipsum" 
    name: "Ipsum"
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    dateStart:
      class: DateTime
      value: "2023-07-05" 
    dateEnd:
      class: DateTime
      value: "2023-07-05"
    dateCreate:
      class: DateTime
      value: "2023-07-05" 
    numberMinPlace: null 
    orderNumber: 1
    type: "limitée"
    partnership: null
  8:
    slug: "8-dolor" 
    name: "Dolor"
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    dateStart:
      class: DateTime
      value: "2023-02-05" 
    dateEnd:
      class: DateTime
      value: "2023-07-05"
    dateCreate:
      class: DateTime
      value: "2023-02-05" 
    numberMinPlace: null
    orderNumber: 7
    type: "limitée"
    partnership: null
  9:
    slug: "9-sit" 
    name: "Sit"
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    dateStart:
      class: DateTime
      value: "2022-08-12" 
    dateEnd:
      class: DateTime
      value: "2023-07-05"
    dateCreate:
      class: DateTime
      value: "2022-08-12" 
    numberMinPlace: null 
    orderNumber: 4
    type: "limitée"
    partnership: null
  10:
    slug: "10-amet" 
    name: "Amet"
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    dateStart:
      class: DateTime
      value: "2021-10-06" 
    dateEnd:
      class: DateTime
      value: "2023-07-05"
    dateCreate:
      class: DateTime
      value: "2021-10-06" 
    numberMinPlace: null
    orderNumber: null
    type: "limitée"
    partnership: null

imageTicketing:
  1:
    name: "patheLogo.png"
    numero: 1
    ticketing:
      entity: ticketing
      id: 1
  2:
    name: "patheGaumont.jpg"
    numero: 2
    ticketing:
      entity: ticketing
      id: 1
  3:
    name: "patheHome.jpg"
    numero: 3
    ticketing:
      entity: ticketing
      id: 1
  4:
    name: "parcAsterix.jpg"
    numero: 1
    ticketing:
      entity: ticketing
      id: 2
  5:
    name: "decathlonMagasin.jpg"
    numero: 1
    ticketing:
      entity: ticketing
      id: 3
  6:
    name: "decathlonPersonnel.jpg"
    numero: 2
    ticketing:
      entity: ticketing
      id: 3
  7:
    name: "romeColisee.jpg"
    numero: 1
    ticketing:
      entity: ticketing
      id: 4
  8:
    name: "romePont.jpg"
    numero: 2
    ticketing:
      entity: ticketing
      id: 4
  9:
    name: "romeVille.jpg"
    numero: 3
    ticketing:
      entity: ticketing
      id: 4
  10:
    name: "romeVoyage.jpg"
    numero: 4
    ticketing:
      entity: ticketing
      id: 4
  11:
    name: "conventionManga.jpg"
    numero: 1
    ticketing:
      entity: ticketing
      id: 5
  12:
    name: "lorem.png"
    numero: 1
    ticketing:
      entity: ticketing
      id: 6
  13:
    name: "ipsum.png"
    numero: 1
    ticketing:
      entity: ticketing
      id: 7
  14:
    name: "dolor.jpg"
    numero: 1
    ticketing:
      entity: ticketing
      id: 8
  15:
    name: "sit.png"
    numero: 1
    ticketing:
      entity: ticketing
      id: 9
  16:
    name: "amet.jpg"
    numero: 1
    ticketing:
      entity: ticketing
      id: 10

survey:
  1:
    question: "Aimeriez-vous avoir des déjeuner tous les matins ?"
    isActive: 0
    datetime:
      class: DateTime
      value: "2023-03-07 15:37:33"
    nbVote: 5
  2:
    question: "Quel est votre fastfood préféré ?"
    isActive: 0
    datetime: 
      class: DateTime
      value: "2023-04-12 09:30:00"
    nbVote: 5
  3:
    question: "Quel est votre parc d'attraction préféré ?"
    isActive: 0
    datetime:
      class: DateTime
      value: "2022-12-07 18:00:00"
    nbVote: 5
  4:
    question: "Quelle est la couleur du cheval blanc d'Henri 4 ?"
    isActive: 0
    datetime:
      class: DateTime
      value: "2023-01-07 12:00:00"
    nbVote: 5
  5:
    question: "Quelle est la couleur de tes chaussettes ?"
    isActive: 1
    datetime:
      class: DateTime
      value: "2023-04-19 15:00:00"
    nbVote: 5

response:
  1:
    text: "Toujours"
    survey:
      entity: survey
      id: 1
    nbVote: 1
  2:
    text: "Jamais"
    survey:
      entity: survey
      id: 1
    nbVote: 2
  3:
    text: "De temps en temps"
    survey:
      entity: survey
      id: 1
    nbVote: 2
  4:
    text: "McDo"
    survey:
      entity: survey
      id: 2
    nbVote: 2
  5:
    text: "Burger King"
    survey:
      entity: survey
      id: 2
    nbVote: 2
  6:
    text: "KFC"
    survey:
      entity: survey
      id: 2
    nbVote: 1
  7:
    text: "Disney"
    survey:
      entity: survey
      id: 3
    nbVote: 1
  8:
    text: "Parc Astérix"
    survey:
      entity: survey
      id: 3
    nbVote: 3
  9:
    text: "La mer de sable"
    survey:
      entity: survey
      id: 3
    nbVote: 1
  10:
    text: "Rouge"
    survey:
      entity: survey
      id: 4
    nbVote: 4
  11:
    text: "Blanc"
    survey:
      entity: survey
      id: 4
    nbVote: 1
  12:
    text: "Noir"
    survey:
      entity: survey
      id: 4
    nbVote: 0
  13:
    text: "Bleues"
    survey:
      entity: survey
      id: 5
    nbVote: 1
  14:
    text: "Vertes"
    survey:
      entity: survey
      id: 5
    nbVote: 1
  15:
    text: "Jaunes"
    survey:
      entity: survey
      id: 5
    nbVote: 3
  16:
    text: "Grises"
    survey:
      entity: survey
      id: 5
    nbVote: 0
  17:
    text: "Mauves"
    survey:
      entity: survey
      id: 5
    nbVote: 0

userResponse:
  1:
    datetime:
      class: DateTime
      value: "2023-03-07 15:37:33"
    response:
      entity: response
      id: 1
  2:
    datetime:
      class: DateTime
      value: "2023-03-07 12:25:58"
    response:
      entity: response
      id: 2
  3:
    datetime:
      class: DateTime
      value: "2023-03-07 09:37:21"
    response:
      entity: response
      id: 3
  4:
    datetime:
      class: DateTime
      value: "2023-03-07 11:34:33"
    response:
      entity: response
      id: 2
  5:
    datetime:
      class: DateTime
      value: "2023-03-07 15:41:11"
    response:
      entity: response
      id: 3
  6:
    datetime:
      class: DateTime
      value: "2023-03-07 17:58:19"
    response:
      entity: response
      id: 4
  7:
    datetime:
      class: DateTime
      value: "2023-03-07 16:46:16"
    response:
      entity: response
      id: 5
  8:
    datetime:
      class: DateTime
      value: "2023-03-07 08:32:25"
    response:
      entity: response
      id: 5
  9:
    datetime:
      class: DateTime
      value: "2023-03-07 03:23:29"
    response:
      entity: response
      id: 6
  10:
    datetime:
      class: DateTime
      value: "2023-03-07 11:10:21"
    response:
      entity: response
      id: 4
  11:
    datetime:
      class: DateTime
      value: "2023-03-07 16:14:35"
    response:
      entity: response
      id: 7
  12:
    datetime:
      class: DateTime
      value: "2023-03-07 23:23:23"
    response:
      entity: response
      id: 9
  13:
    datetime:
      class: DateTime
      value: "2023-03-07 22:22:22"
    response:
      entity: response
      id: 8
  14:
    datetime:
      class: DateTime
      value: "2023-03-07 15:41:46"
    response:
      entity: response
      id: 8
  15:
    datetime:
      class: DateTime
      value: "2023-03-07 12:12:41"
    response:
      entity: response
      id: 8
  16:
    datetime:
      class: DateTime
      value: "2023-03-07 14:06:10"
    response:
      entity: response
      id: 10
  17:
    datetime:
      class: DateTime
      value: "2023-03-07 19:39:15"
    response:
      entity: response
      id: 10
  18:
    datetime:
      class: DateTime
      value: "2023-03-07 20:01:13"
    response:
      entity: response
      id: 10
  19:
    datetime:
      class: DateTime
      value: "2023-03-07 21:05:31"
    response:
      entity: response
      id: 10
  20:
    datetime:
      class: DateTime
      value: "2023-03-07 00:45:49"
    response:
      entity: response
      id: 11
  21:
    datetime:
      class: DateTime
      value: "2023-03-07 05:49:12"
    response:
      entity: response
      id: 14
  22:
    datetime:
      class: DateTime
      value: "2023-03-07 06:36:14"
    response:
      entity: response
      id: 13
  23:
    datetime:
      class: DateTime
      value: "2023-03-07 09:42:21"
    response:
      entity: response
      id: 15
  24:
    datetime:
      class: DateTime
      value: "2023-03-07 10:16:46"
    response:
      entity: response
      id: 15
  25:
    datetime:
      class: DateTime
      value: "2023-03-07 12:19:57"
    response:
      entity: response
      id: 15

contact:
  1:
    firstname: "Wyoming"
    name: "Blachard"
    email: "pede@icloud.couk"
    subject: "Désincription newsletter"
    message: "Bonjour, je souhaite me désinscrire de la newslettter, merci."
    consent: 1
    dateSend:
      class: DateTime
      value: "2023-07-05"
  2:
    firstname: "Dorian"
    name: "Baker"
    email: "proin.sed.turpis@protonmail.edu"
    subject: "Désincription newsletter"
    message: "Je ne suis plus intéressé par la newsletter, merci."
    consent: 1
    dateSend:
      class: DateTime
      value: "2023-07-05"
  3:
    firstname: "Ignatius"
    name: "Chavez"
    email: "nonummy.ac@icloud.edu"
    subject: "Inscription newsletter"
    message: "Bonjour, je souhaite m'inscrire merci."
    consent: 1
    dateSend:
      class: DateTime
      value: "2023-07-05"
  4:
    firstname: "Finn"
    name: "Conner"
    email: "luctus@icloud.ca"
    subject: "Stage"
    message: "Bonjour, je souhaite postuler pour un stage."
    consent: 1
    dateSend:
      class: DateTime
      value: "2023-07-05"
  5:
    firstname: "Aretha"
    name: "Baker"
    email: "bibendum.sed@protonmail.com"
    subject: "Offre intéressante"
    message: "Bonjour, je suis intéréssé par l'une de vos offres !"
    consent: 1
    dateSend:
      class: DateTime
      value: "2023-07-05"

subscriber:
  1:
    email: "malesuada.fames@aol.net"
    consent: 1
  2:
    email: "integer.in.magna@yahoo.edu"
    consent: 1
  3:
    email: "erat.eget@protonmail.net"
    consent: 1
  4:
    email: "faucibus@icloud.org"
    consent: 1
  5:
    email: "vestibulum@outlook.couk"
    consent: 1